# -*- coding: utf-8 -*-
"""Untitled30.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v9GoVYUjYCYj7MaYwLnwdBl_RFOGqG5m
"""

import numpy as np
import matplotlib.pyplot as plt
 
def line_gen(A,B):
  len =10
  x_AB = np.zeros((2,len))
  lam_1 = np.linspace(0,1,len)
  for i in range(len):
    temp1 = A + lam_1[i]*(B-A)
    x_AB[:,i]= temp1.T
  return x_AB
 
x = np.linspace(-5,5,100)
y=-(x*x)/12
plt.plot(x,y,label='$x^2=-12y$')
plt.xlabel('$x$')
plt.ylabel('$y$')
 
#Plotting directrix
#equation of directrix is given y=3
P=np.array([13,3])
Q=np.array([-13,3])
A=line_gen(P,Q)
plt.plot(A[0,:],A[1,:],label='$directrix$')
 
#plotting focus
plt.plot(0,-3,'o',label='$focus$')
plt.text(0.2,-3.2,'F')
plt.legend(loc='best')
plt.grid()
plt.xlim([-7,7])
 
 
plt.show()